baseURL: https://aafu.pages.dev/
languageCode: en-us
build:
  writeStats: true
params:
  title: Portfolio
  author: Sari Itani
  description: Personal Porftolio
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  favicons:
    use: true
    metas: |2-
              <link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
              <link rel="icon" type="image/gif" sizes="32x32" href="./bongocat.gif">
              <link rel="icon" type="image/gif" sizes="16x16" href="./bongocat.gif">
              <link rel="manifest" href="site.webmanifest">
              <link rel="mask-icon" href="safari-pinned-tab.svg" color="#252627">
              <link rel="shortcut icon" href="./bongocat.gif">

  profile:
    name: "Sari Itani"
    tagline: Computer Engineer - AI expertise
    location: "Aramoun, Lebanon"
    email: sariitani101@gmail.com
    photo: pfp.jpg
  social:
    title: Links
    list:
      - icon: fab fa-linkedin-in
        url: "https://www.linkedin.com/in/sari-itani-868481200"
        title: LinkedIn
      - icon: fab fa-github
        url: "https://www.github.com/SariItani"
        title: GitHub
      - icon: fab fa-orcid
        url: "https://orcid.org/0009-0007-7886-510X"
        title: Orcid
      - icon: fab fa-whatsapp
        url: "https://wa.link/a9h48p"
        title: Whatsapp
      - icon: fas fa-envelope
        title: Email
        url: "mailto:sariitani101@gmail.com"
  showInAccordion:
    - item: aboutme
      expand: true
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: proposals
    - item: skill
    - item: hobby
  aboutme:
    title: About Me
    icon: fas fa-user
    description: Highly motivated and results-oriented Computer Engineer, specialized in Artificial Intelligence and passionate about backend development, constantly seeking a challenging position to leverage my technical expertise and contribute to intelligent and efficient computer systems.
  experience:
    title: Leadership & Management
    icon: fas fa-briefcase
    list:
      - position: President
        dates: 2023 - *Present*
        company: ARC & IEEE-CIS
        url: "https://www.instagram.com/bau_arc/"
        details: |1-
          Check out my blog post on [strategies to run ARC and IEEE-CIS](./blog/post_3/)
          - *Launch, March 2023*: The group who worked on the ["Cafeteria Madness"](https://github.com/SariItani/BAU-Engineering-Day) game formed the AI and Robotics club (ARC) committee and showcased the game during launch and accepted applications for people to start joining the ARC club.
          - *Engineering Day, May 2023*: We got recognised as an established club by the faculty of engineering by receiving a certificate.
          - *Orientation, August 2023*: We showcased, in a short presentation, What ARC is and Why students would want to join ARC, accepting registration applications from the new first year students.
          - *Booth, September 2023*: We Annuonced our main plans for the semester in the form of a road map, showcased What ARC is and Why students would want to join, and accepted new registration applications.
          - *AI and Robotics Debate & Trivia day, October 2023*: It was a failed attempt to start weekly or monthly club meetings, we debated a broad pool of topics and voted for those who got a point and in the end announced which side wins for each topic.
          - *Ethical Hacking, October 2023*: We collabed with Semicolon-Academy to introduce students to the area of cybersecurity in an interactive seminar.
          - *ROS2, November 2023*: We collabed with Eng. Abboud Hayek to introduce students to the area of robotics and showcase robotics development with ROS2 framework.
          - *NLP, November 2023*: We collabed with Eng. Lara Wehbe to introduce students to the area of NLP in AI and showcase the process of an LLM.      
          - *Innovation, December 2023*: We collabed with DR. Ahmad El Hajj to spread awareness on the importance of innovating in our university years especially as engineering students.
          - *Huawei HCAI, December 2023*: Logistics Management ofthe program.
          - *Launch, April 2024*: ARC club was expanding and required financial support for upcoming ambitious projects, so ARC became IEEE Computational Intelligence Society (CIS) student branch.
          - *Zaka/Beirut AI Workshop, May 2024*: IEEE Computational Intelligence Society collaborated with Zaka AI to deliver an extensive workshop entitled "AI development: from university knowledge to workplace skills", which is self explanatory, introducing the tech stacks and skills and workflows that an AI engineer does on the job.
      - position: Co-founder
        dates: 2023 - *Present*
        company: LOOP
        url: "https://www.instagram.com/theloop.lb"
        details: |1-
          - Loop is an unofficial alliance of all student bodies in universities related to computer majors
          - Devised my previous [strategies](./blog/post_3/) from ARC & IEEE-CIS to help organize 2 nationwide events: a game jam on April 20th 2024, and an AI hackathon during the fall semester of 2024-2025
          - Held meetings and jotted down meeting minutes discussing the scalability and potential of LOOP's events and what sort of outreach and success LOOP could opt for.
  education:
    title: Competitions
    icon: fas fa-medal
    list:
      - degree: LAU IEEE-Robotics D.A.R.E
        college: Lebanese American University
        dates: April 27, 2024
        thesis_title: "Developing a cheap yet efficient wildfire surveillance system to quickly scan the area and generate a priority zone that would instruct fire fighters to most optimally stop the fire, based on aerial images and environmental data and critical conditions such as presence of casualties and human residence, hence saving time and lives."
      - degree: LAU Case Competiton
        college: Lebanese American University
        dates: June 9, 2023
        thesis_title: "''Revolutionizing Lebanese Tourism: Embrace the Hunt Campaign'' Spearheaded the development and execution of an AR-enabled scavenger hunt campaign aimed at promoting Lebanon as a top travel destination, and Orchestrated a multi-channel marketing strategy and collaborated with diverse stakeholders to drive engagement and stimulate economic growth through immersive tourism experiences."
        thesis_url: "https://drive.google.com/file/d/1uS6bXf34LMHY2P91r6vDBR12HBPhoJB8/view?usp=sharing"
      - degree: Huawei ICT-AI
        college: Huawei (MENA)
        dates: February 2024
        thesis_title: "Language translation and voice generation have seen significant advancements, but current systems often lack the ability to capture the subtleties of human speech. This project proposes a solution that combines transformer-based language translation models with voice cloning techniques to deliver a more immersive and authentic translation experience. By utilizing the power of cloud-based AI platforms, real-time audio interception, and deep learning algorithms, our system aims to generate voiceovers that mirror the speaker's tone, mood, and pitch in the target language. With a user- friendly interface and a focus on maintaining privacy and ethical standards, our solution addresses the limitations of existing automatic translation systems and strives to provide a professional and engaging communication tool."
        thesis_url: "https://github.com/Leboweeb/Scoltia-Realtime-Voice-Translation-for-Teams"
      - degree: NeurIPS 2023 Machine Unlearning
        college: Kaggle
        dates: Novemeber 2023
        thesis_title: "The main objective of this competition is to develop an algorithm that takes an AI model and a forget set, part of the training set, leaving behind the retain set, and returns an AI model that’s as closely accurate as the original given model, but the effect of the forget set will be deprecated so that its influence is almost null, meaning that the accuracy on the forget set should approach zero."
        thesis_url: "https://drive.google.com/file/d/145EBI-Z9WfegppMqmYXoVa3J0WiSFju8/view?usp=drive_link"
  publication:
    title: Freelance
    icon: fas fa-handshake
    types:
      - Website
      - AI
      - Data Science
    list:
      - title: YMY Management System
        url: "https://sariitani.pythonanywhere.com/"
        description: A business management website for YMY, encapsulating their management processes and automated data entry with Twilio API for WhatsApp Business. It covers a rich backend that 
        type: Website
      - title: BioGenie
        url: "https://srisri.pythonanywhere.com/"
        description: A nice website with an easy user interface, and a playful and interactive frontend design, integrated with a chatbot using OpenAI API that helps assess Lebanese LS students's biology knowledge by answering MCQ questions, provoding all the necessary materials to improve.
        type: Website
      - title: Musical Instruments HTML views
        url: "https://github.com/SariItani/Music-Information-HTML/"
        description: A basic freelance HTML page for a fundamentals course final based in Canada. The aim was to grasp most of the HTML features.
        type: Website
      - title: Nollini (discontinued)
        type: Website
        url: "https://github.com/SariItani/Nollini--discontinued-"
        description: An Ecommerce static website that hooks a target market of Lebanese employees based in Lebanon with copy-A European distributers through submitting and showcasing their products on one central hub.
      - title: Blood Donnation Website
        type: Website
        url: "https://github.com/SariItani/Blood-Donnation-Flask-App"
        description: A simple freelance blood donnation flask app for a software engineering course. Implements required functionalities learned through the course and advanced user authentication and security standards.
      - title: Image Recognition with CV2
        type: AI
        url: "https://github.com/SariItani/ImageCV2Detection-of-Matchboxes"
        description: Freelance computer vision project. OpenCV2 script to detect matches based on a HAAR Cascade fine tuned model, with the fine tuning dataset being normal images of matchboxes.
      - title: Parkinsons Disease Data Acquisition and Preprocessing
        type: Data Science
        description: "Helped with devising a PhD student's research on parkinsons' disease, by providing state-of-the-art datasets for AI training freely available on the internet, for the follwing data types 'EEG', 'EMG', 'X and Y for leg movement', 'voice', and 'Handwriting'"
  project:
    title: Projects
    icon: fas fa-project-diagram
    list:
      - title: Cafeteria Madness
        url: "https://github.com/SariItani/BAU-Engineering-Day"
        description: The player does not need a controller to play. An AI model can scan his hand gestrues and map regular patterns to in game player-environment interactions. Demonstrated in the game 'Cafeteria Calamity'. A team of 4, we made everything, from art to music to code.
      - title: Recipe Sharing Platform
        url: "https://github.com/SariItani/BAUSpring2024SoftwareEngProject"
        description: The project entails the development of a recipe sharing platform that aims to simplify the process of meal planning and recipe discovery for users. This platform can potentially be extended to mobile devices, catering to a wider audience and enhancing accessibility. The primary objective is to provide users with a user-friendly interface where they can easily search for recipes based on ingredients, preferences, dietary requirements, and available kitchen equipment. Additionally, the platform will include features for recommndations uisng AI recommender systems and tracking health and nutrition, such as calorie intake monitoring, through an intuitive dashboard design.
      - title: Better Moodle
        url: "https://github.com/StunningSamuel/BetterMoodle"
        description: Moodle platform can be quite challanging to use, and this difficulty becomes a real issue that all BAU students suffer from during online course reistration. The issue is that the servers at the university are outdated and cannot handle the traffic. Thus, Better Moodle is a mobile flutter app that provides utilities to work aroudn this issue, such as regular caches from the moodle website, like schedule and course offering, notifications when anything is posted on moodle website, and automation services like automated registration with course code list input.
      - title: Cifar10 Resnet18 Image Classification 
        url: "https://github.com/SariItani/Cifar10Resner18"
        description: Training an AI model to classify images from the Cifar10 dataset with Resnet18 architecture.
      - title: ARC website
        url: "https://github.com/Leboweeb/Engineering-Day-Website"
        description: ARC needed automated processing and various other features like information and blogs and links and stories and media etc... You get it, just what any club needs, a centralized server running managing the process of running the ARC club fully.
      - title: Gym Management System
        url: "https://github.com/SariItani/gym-manager"
        description: A Solo project i made to learn Django and Flask, and web development in general. This website manages the gym operations fully, from its employees to its clients. To employees, it is a business management system, but to the users it is simply an ecomerce/dashboard analytics web application.
      - title: NVIDIA Canvas API with GUI
        url: "https://github.com/SariItani/Sketching-Website-engday"
        description: The university owns a super computer capable of running the NVIDIA Canvas app, but most students weren't allowed in the lab without priviliges like being a computer engineering student. Thus, in a due, me and my best friend created an API that links university students on the same network as the Engineering Faculty Labs to the NVIDIA Canvas application found on the super computer, through a 
      - title: CLI Java Password Manager
        url: "https://github.com/SariItani/Password-Manager-Java-App"
        description: as
  proposals:
    title: Proposals & Research
    icon: fas fa-tasks
    list:
      - title: Robot Mania
        # url: "#"
        description: In a planned [ARC](https://www.instagram.com/bau_arc/) event, an obstacle course is randomly generated, and 2 teams are supposed to compete against one another by building a robot and training its movements using reinforcement learning, or by hardcoding its movements, so that the controls are managed by ROS2 operating system that will run the Genetic Algorithm on both team's robots and attempt to pass the obstacle course fair and square. This experience is proposed to be gamified using Unity and published on [itch.io](https://itch.io).
      - title: Project 2
        url: "#"
        description: Description of the project
      - title: Project 3
        url: "#"
        description: Description of the project
      - title: Project 4
        url: "#"
        description: Description of the project
  skill:
    title: Skills
    panelId: skill-panel
    icon: fas fa-laptop-code
    list:
      - skill: "Skill 1, Skill 2"
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
  hobby:
    title: Music
    icon: fas fa-music
    list:
      - hobby: file1
      - hobby: file2
      - hobby: file3
